version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - DOCKER_TLS_VERIFY=0
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  pgdata: {}
networks:
  app_network:
    driver: bridge
